################################## Experiment Configuration #######################################
batch_log_frequency: 200

##################################### Data Configuration ##########################################

# The name of the dataset - Either "metr_la" or "pems_bay"
dataset: pems_bay

valid_percentage: .1

test_percentage: .2

# There's around 32K points - ~20k train, ~6k valid, ~6k test
sample_dataset: False

# These sampling factors leave 32/32/32 samples in train/valid/test - Just for quick experimentation purposes.
sample_train_factor: 0.016
sample_valid_factor: 0.0072
sample_test_factor: 0.0024

batch_size: 32

################################### Optimizer Configuration ########################################
# Number of epochs for training
n_epochs: 250

# Optimizer (str, sgd/rmsprop/adam/adamax)
optimizer: adam

# Learning rate of the optimizer
lr: 0.002

beta_1: 0.9
beta_2: 0.98
eps: 0.000000001

# Early stopping patience
early_stop_patience: 25

##################################### Model Configuration ##########################################

# [adn_base]
model_type: adn_base

attention_config:
  lsh:
    bucket_size: 16
    n_hashes: 8
  linear:
    eps: 0.0001
  linformer:
    k: 32


# Dropout rate of the model (float, <1.)
p_dropout: .3

# Number of attention heads (int) {heads}
n_heads: 4

n_blocks: 3

##################################### Traffic Task Configuration #######################
n_previous_steps: 12

n_future_steps: 12

n_features: 12

################################ ADN ###################################################

d_features: 1
d_hidden: 32
d_feedforward: 256