################################## Experiment Configuration #######################################
batch_log_frequency: 5

##################################### Data Configuration ##########################################

# The name of the dataset - Either "metr_la" or "pems_bay"
dataset: metr_la

valid_percentage: .1

test_percentage: .2

# There's around 32K points - ~20k train, ~6k valid, ~6k test
sample_dataset: True

# These sampling factors leave 32/32/32 samples in train/valid/test - Just for quick experimentation purposes.
sample_train_factor: 0.016
sample_valid_factor: 0.0072
sample_test_factor: 0.0024

batch_size: 2

################################### Optimizer Configuration ########################################
# Number of epochs for training
n_epochs: 1

# Optimizer (str, sgd/rmsprop/adam/adamax)
optimizer: adam

# Learning rate of the optimizer
lr: 2e-3

beta_1: 0.9
beta_2: 0.98
eps: 0.000000001

# Early stopping patience
early_stop_patience: 10

##################################### Model Configuration ##########################################

# [adn]
model_type: adn_base

# [full, group, lsh, favorplus, efficient, linear]
attention_type: full

attention_config:
  lsh:
    bucket_size: 8
    n_hashes: 8
  linear:
    eps: 0.0001
  linformer:
    k: 32

linformer_k: 16

# Dropout rate of the model (float, <1.)
p_dropout: .3

# Number of attention heads (int) {heads}
n_heads: 8

n_blocks: 1

##################################### Traffic Task Configuration #######################
n_previous_steps: 12

n_future_steps: 12

n_features: 12

################################ ADN ###################################################

d_features: 1
d_hidden: 8
d_feedforward: 8

normalize_all: False

normalized_loss: False

autoregressive_validation: False